config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'

  devise_for :users #controllers: {
  #   omniauth_callbacks: 'users/omniauth_callbacks'
  # }
  resources :users, only: [:show, :update, :new, :create, :edit] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  put "/users/:id/hide" => "users#hide", as: 'users_hide'
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :rooms, only: [:create, :show, :index]
  resources :chats, only: [:create]
  resources :events do
    resource :event_users, only: [:create, :destroy]
    resources :event_comments, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :sns_credentials, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :event_comments, dependent: :destroy
  has_many :event_users, dependent: :destroy

  attachment :profile_image

  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable, :timeoutable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed

  has_many :entries, dependent: :destroy
  has_many :chats, dependent: :destroy

  validates :name, presence: true, length: { in: 2..8 }, on: :update

  def follow(user_id) #フォローする
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id) #フォローを外す
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user) #フォローしていればtrue
    followings.include?(user)
  end

  def active_for_authentication? #退会済みなら弾く
    super && (self.is_delete == false)
  end

  # def self.without_sns_data(auth)
  #   user = User.where(email: auth.info.email).first

  #   if user.present?
  #     sns = SnsCredential.create(
  #       uid: auth.uid,
  #       provider: auth.provider,
  #       user_id: user.id
  #     )
  #   else
  #     user = User.new(
  #       # nickname: auth.info.name,
  #       email: auth.info.email,
  #     )
  #     sns = SnsCredential.new(
  #       uid: auth.uid,
  #       provider: auth.provider
  #     )
  #   end
  #   return { user: user ,sns: sns}
  # end

  # def self.with_sns_data(auth, snscredential)
  #   user = User.where(id: snscredential.user_id).first
  #   unless user.present?
  #     user = User.new(
  #       # nickname: auth.info.name,
  #       email: auth.info.email,
  #     )
  #   end
  #   return {user: user}
  # end

  # def self.find_oauth(auth)
  #   uid = auth.uid
  #   provider = auth.provider
  #   snscredential = SnsCredential.where(uid: uid, provider: provider).first
  #   if snscredential.present?
  #     user = with_sns_data(auth, snscredential)[:user]
  #     sns = snscredential
  #   else
  #     user = without_sns_data(auth)[:user]
  #     sns = without_sns_data(auth)[:sns]
  #   end
  #   return { user: user ,sns: sns}
  # end

  enum sex: { "男性" =>0, "女性" =>1 }
  enum style: { "スノーボーダー" =>0, "スキーヤー" =>1, "その他" =>2 }
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  # password = Devise.friendly_token.first(7)
  #   if session[:provider].present? && session[:uid].present?
  #     @user = User.create(email: session[:email], password: "password", password_confirmation: "password")
  #     sns = SnsCredential.create(user_id: @user.id,uid: session[:uid], provider: session[:provider])
  #   else
  #     @user = User.create(email: session[:email], password: session[:password], password_confirmation: session[:password_confirmation])
  #   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  require 'happybirthday'

  def show
    @user = User.find(params[:id])
    birthday = Happybirthday.born_on(current_user.birthday)
    @user.birthday = birthday.age.years_old
    @current_user = current_user
    @posts = @user.posts
    # DM処理
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true #ルーム作成
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom #ルーム作成
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def first_edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to posts_path
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to posts_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render "edit"
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    redirect_to posts_path
  end

  def hide
    @user = User.find(params[:id])
    #is_deletedカラムにフラグを立てる(defaultはfalse)
    @user.update(is_delete: true)
    if @user.is_delete == true
      @user.destroy
    end
    #ログアウトさせる
    sign_out
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end

  private

  def user_params
     params.require(:user).permit(:name, :profile_image, :style, :birthday, :sex, :introduction)
  end
end

app/views/users/_chat.html.erb
  <!--< % if (current_user.followed_by? @user) && (@user.followed_by? current_user)  %>--><!--相互フォローの場合-->
<% if isRoom == true %><!-- 既存のチャットがある時-->
  <%= link_to room_path(roomId)  do %>
    <i class="far fa-envelope message-icon"></i>
  <% end %>
<% else %>
  <%= form_with model: room, local: true, class: 'message-form' do |f| %>
    <%= fields_for entry do |e| %>
    <%= e.hidden_field :user_id, value: user.id %>
    <% end %>
    <%= button_tag type: 'submit', class: 'btn' do %>
      <i class="far fa-envelope message-icon"></i>
    <% end %>
  <% end %>
<% end %>

app/views/users/_icons.html.erb
<% posts.reverse.each do |post| %>
  <!--プロフィール部分-->
  <div class="post_content post-index_<%= post.id %>">
	  <div class="post decoration">
	  	<%= link_to post_path(post), class: "under-line" do %>
		  	<p class="post-text mt-3 ml-3"><%= truncate(post.content, length: 50) %></p>
		  <% end %>
	  </div>
	  <div>
	  	<!--いいね-->
		  <span id="bottons_<%= post.id %>"><%= render 'layouts/favorites_icon', post: post %></span>
			<!--こめんと-->
			<span id="bottons_<%= post.id %>"><%= render 'layouts/comments_icon', post: post %></span>
			<!--削除-->
			<span id="bottons_<%= post.id %>"><%= render 'layouts/delete_icon', post: post %></span>
		</div>
  <hr>
  </div>
<% end %>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
          <% if current_user != user %>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_profile.html.erb
<%= link_to user_path(user), class: "under-line" do %>
  <%= attachment_image_tag user, :profile_image, size: "70x70", fallback: 'no_image.jpg', format: 'jpeg', class: "rounded-circle" %>
  <span class="user-name"><%= user.name %></span>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-sm-3 line-left">
    <%= render "devise/shared/back" %>
    <div class="side-bar">
      <%= render "devise/shared/side_links" %>
    </div>
  </div>
  <div class="col-sm-9 main py-4">
    <div class="edit-profile">
    <h3 class="page-title text-center py-2"><i class="fas fa-user-cog"></i>プロフィール編集</h3>
    <%= form_with model:@user, url: user_path(@user), local:true do |f| %>
    <%= render "layouts/errors", model: @user %>
      <div class="field mt-3">
        <span class="font-weight-bold"><%= f.label :ニックネーム %></span><br/>
        <%= f.text_field :name, class: "edit-field" %>
      </div>
      <div class="field mt-3">
        <span class="font-weight-bold"><%= f.label :プロフィール画像 %></span><br/>
        <%= f.attachment_field :profile_image, class: "edit-field image-border" %>
      </div>
      <div class="field mt-3">
        <span class="font-weight-bold"><%= f.label :生年月日 %></span><br/>
        <%= f.date_select :birthday, use_month_numbers: true,start_year: 1930, end_year: (Time.now.year - 10), default: Date.new(1997, 1, 1) %>
      </div>
      <div class="field mt-3">
        <span class="font-weight-bold">性別</span>
        <div class="radio-inline">
          <%= f.radio_button :sex, :男性, checked: "checked" %>
          <%= f.label :男性, class: "job_type_label" %>
          <%= f.radio_button :sex, :女性 %>
          <%= f.label :女性, class: "job_type_label" %>
        </div>
      </div>

      <div class="field mt-3">
      <span class="font-weight-bold">スタイル</span>
        <div class="radio-inline">
          <%= f.radio_button :style, :スノーボーダー, checked: "checked" %>
          <%= f.label :スノーボーダー %>
          <%= f.radio_button :style, :スキーヤー %>
          <%= f.label :スキーヤー, class: "job_type_label" %>
          <%= f.radio_button :style, :その他 %>
          <%= f.label :その他, class: "job_type_label" %>
        </div>
      </div>

      <div class="field mt-3">
       <span class="font-weight-bold"><%= f.label :自己紹介文 %></span><br/>
        <%= f.text_area :introduction , class: "edit-field", rows: 7 %>
      </div>
      <div class="filed mt-3 text-left">
        <%= f.submit '更新', class: "btn btn-primary event-filed" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-sm-3 left-line">
    <%= render "devise/shared/back" %>
    <div class="side-bar">
      <%= render "devise/shared/side_links" %>
      <% unless current_user == @user %>
      <%= render "devise/shared/my_profile", current_user: @current_user %>
      <% end %>
    </div>
  </div>
  <div class="col-sm-6 py-4 main">
    <div class="profile-show">
      <%= attachment_image_tag @user, :profile_image, size: "100x100", fallback: 'no_image.jpg', size: '100x100', format: 'jpeg', class: "rounded-circle" %>
      <span class="name ml-3 mt-2 user-show-name"><%= @user.name %></span>
      <span class="ml-3 font-s"><%= @user.birthday %>歳</span>
      <span class="ml-2 font-s"><%= @user.sex %></span>
      <span class="font-s last-sign-in">
        <%# if @user.logged_in?(@user) %>
          <!--<i class="fas fa-circle" style="color: green;"></i>ログイン中-->
        <%# else %>
          <i class="fas fa-circle" style="color: red;"></i><%= time_ago_in_words(@user.current_sign_in_at) %>前
        <%# end %>
      </span>
    </div>

    <div class="follow-form">
    <% if current_user != @user %>
      <%= render '/users/chat', user: @user, isRoom: @isRoom, roomId: @roomId, room: @room, entry: @entry %>
      <span id="bottons_<%= @user.id %>"><%= render 'layouts/follow', user: @user %></span>
    <% else %>
      <%= link_to edit_user_path(@user) do %>
        <i class="fas fa-user-cog mt-3">プロフィール編集</i>
      <%= link_to "退会", users_hide_path(current_user), method: :put, data:
      {confirm:  '一度退会するとデータは戻りません。</br>本当に退会しますか?', cancel: 'キャンセル', commit: '退会'}, title: '退会確認', class: "btn btn-outline-danger follow-btn" %>
      <% end %>
    <% end %>
    </div>

    <hr>

    <div>
      <%= link_to user_followings_path(@user), class: "btn" do %>
        <span class="follow-text"><%= @user.followings.count %></span>
        <span class="follow-text">フォロー</span>
      <% end %>

      <%= link_to user_followers_path(@user), class: "btn" do  %>
        <span class="follow-text"><%= @user.followers.count %></span>
        <span class="follow-text">フォロワー</span>
      <% end %>
    </div>
    <hr>
      <h4 class="font-m font-weight-bold">スタイル</h4>
      <p class="ml-3"><%= @user.style %></p>
    <hr>
      <h4 class="font-m font-weight-bold">自己紹介</h4>
      <p class="ml-3"><%= @user.introduction %></p>
    <hr>
  </div>
  <div class="col-sm-3 right-bar">
    <h4 class="sub-title text-center py-1"><i class="fas fa-bullhorn"></i></i>投稿</h4>
    <div>
      <%= render '/users/icons', posts: @posts %>
    </div>

  </div>
</div>