config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'

  devise_for :users #controllers: {
  #   omniauth_callbacks: 'users/omniauth_callbacks'
  # }
  resources :users, only: [:show, :update, :new, :create, :edit] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  put "/users/:id/hide" => "users#hide", as: 'users_hide'
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :rooms, only: [:create, :show, :index]
  resources :chats, only: [:create]
  resources :events do
    resource :event_users, only: [:create, :destroy]
    resources :event_comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

   validates :message, presence: true, length: { maximum: 80 }

end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :event_comments, dependent: :destroy
  has_many :event_users, dependent: :destroy

  validates :title, presence: true, length: { maximum: 38 }
  validates :content, presence: true
  validates :etd, presence: true
  validates :eta, presence: true
  validates :preiod, presence: true

  def count_by?(event)
    (event.recruitment > event.event_users.count) && event.preiod > Time.now
  end

  def applied_by?(user)
    event_users.where(user_id: user.id).exists?
  end

end

app/models/event_comment.rb
class EventComment < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :content, presence: true, length: { maximum: 120 }

end

app/models/event_user.rb
class EventUser < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :post
  
  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  attachment :post_image

  validates :content, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  attachment :image
  
  validates :content, presence: true, length: { maximum: 120 }
  
  def favorited_by?(user)  
    favorites.where(user_id: user.id).exists?
  end
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User" #followerモデルは存在しないためUserモデルをbelongs_toする
  belongs_to :followed, class_name: "User"

  validates :followed_id, presence: true
  validates :follower_id, presence: true

end

app/models/room.rb
class Room < ApplicationRecord

  has_many :entries, dependent: :destroy
  has_many :chats, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :sns_credentials, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :event_comments, dependent: :destroy
  has_many :event_users, dependent: :destroy

  attachment :profile_image

  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable, :timeoutable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed

  has_many :entries, dependent: :destroy
  has_many :chats, dependent: :destroy

  validates :name, presence: true, length: { in: 2..8 }, on: :update

  def follow(user_id) #フォローする
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id) #フォローを外す
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user) #フォローしていればtrue
    followings.include?(user)
  end

  def active_for_authentication? #退会済みなら弾く
    super && (self.is_delete == false)
  end

  # def self.without_sns_data(auth)
  #   user = User.where(email: auth.info.email).first

  #   if user.present?
  #     sns = SnsCredential.create(
  #       uid: auth.uid,
  #       provider: auth.provider,
  #       user_id: user.id
  #     )
  #   else
  #     user = User.new(
  #       # nickname: auth.info.name,
  #       email: auth.info.email,
  #     )
  #     sns = SnsCredential.new(
  #       uid: auth.uid,
  #       provider: auth.provider
  #     )
  #   end
  #   return { user: user ,sns: sns}
  # end

  # def self.with_sns_data(auth, snscredential)
  #   user = User.where(id: snscredential.user_id).first
  #   unless user.present?
  #     user = User.new(
  #       # nickname: auth.info.name,
  #       email: auth.info.email,
  #     )
  #   end
  #   return {user: user}
  # end

  # def self.find_oauth(auth)
  #   uid = auth.uid
  #   provider = auth.provider
  #   snscredential = SnsCredential.where(uid: uid, provider: provider).first
  #   if snscredential.present?
  #     user = with_sns_data(auth, snscredential)[:user]
  #     sns = snscredential
  #   else
  #     user = without_sns_data(auth)[:user]
  #     sns = without_sns_data(auth)[:sns]
  #   end
  #   return { user: user ,sns: sns}
  # end

  enum sex: { "男性" =>0, "女性" =>1 }
  enum style: { "スノーボーダー" =>0, "スキーヤー" =>1, "その他" =>2 }
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!

  def create
    @chat = current_user.chats.new(chat_params)
    if @chat.save
      redirect_to request.referer
    else
      flash[:alert] = "送信に失敗しました。"
      redirect_to request.referer
    end
  end

  private
  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  require 'happybirthday'

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def index
    @events = Event.all.order(created_at: :desc)
    @current_user = current_user
  end

  def show
    @event = Event.find(params[:id])
    @event_comment = EventComment.new
    @user = @event.user
    @current_user = current_user
  end


  private
  def event_params
    params.require(:event).permit(:title, :content, :eta, :etd, :preiod, :recruitment, :cost, :destination)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    render layout: false
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/event_users_helper.rb
module EventUsersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/events/_event_comments.html.erb
<% event.event_comments.reverse.each do |event_comment| %>
  <div id="event-comment_index_<%= event_comment.id %>">
    <div class="commenter-profile">
      <%= link_to user_path(event_comment.user.id), class: "btn left-btn" do %>
        <%= attachment_image_tag event_comment.user, :profile_image, fallback: 'no_image.jpg', size: '50x50', format: 'jpeg', class: "rounded-circle" %>
        <span class="commenter-name-position"><%= event_comment.user.name %></span>
      <% end %>
    </div>
    <div>
      <p><%= event_comment.content %></p>
      <% if event_comment.user == current_user %>
      <div>
        <%= link_to event_event_comment_path(event_comment.event, event_comment),  method: :delete, remote: true do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
      <% end %>
    </div>
    <hr>
  </div>
<% end %>

app/views/events/index.html.erb
<div class="row">
  <div class="col-sm-3 left-line">
    <%= render "devise/shared/back" %>
    <div class="side-bar">
      <%= render "devise/shared/side_links" %>
      <%= render "devise/shared/my_profile", current_user: @current_user %>
    </div>
  </div>
  <div class="col-sm-9 main py-4">
    <h3 class="page-title text-center py-2 fixed comment-form"><i class="far fa-calendar-alt"></i>イベント一覧</h3>
    <% @events.each do |event| %>
    <!--<#% binding.pry %>-->
      <div class="event-title">
        <%= link_to event_path(event), class: "under-line-bl" do %>
          <i class="fas fa-snowman"></i>
          <span><%= event.title %></span>
        <% end %>
      </div>
      <div class="eventer-profile">
        <%= link_to user_path(event.user_id), class: "btn" do %>
            <%= attachment_image_tag event.user, :profile_image, size: "50x50", fallback: 'no_image.jpg', format: 'jpeg', class: "rounded-circle" %>
            <span class="eventer-name ml-3"><%= event.user.name %></span>
            <span class="eventer-sex ml-3 font-s"><%= event.user.sex %></span>
        <% end %>
      </div>
      <div class="mt-1 ml-3">
        <%= event.etd.strftime("%m月%d日(%a)") %>
      </div>
    <hr>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<div class="row">
  <div class="col-sm-3 left-line">
    <%= render "devise/shared/back" %>
    <div class="side-bar">
      <%= render "devise/shared/side_links" %>
    </div>
  </div>
  <div class="col-sm-9 py-4 main">
    <h3 class="page-title text-center py-2"><i class="far fa-calendar-plus"></i></i>イベント作成</h3>
    <%= form_with model: @event, local:true do |f| %>
      <%= render "layouts/errors", model: @event %>
      <div class="filed mt-3">
        <span class="font-weight-bold"><%= f.label :タイトル %></span><br>
        <%= f.text_field :title, placeholder: "タイトル(38文字以内)", class: "event-filed" %>
      </div>
      <div class="filed mt-3">
        <span class="font-weight-bold"><%= f.label :詳細 %></span><br>
        <%= f.text_area :content, placeholder: "入力してください", class: "event-filed", rows: 7 %>
      </div>
      <div class="filed mt-3">
        <span class="font-weight-bold"><%= f.label :出発予定日時 %></span><br>
        <%= f.datetime_field :etd %>
      </div>
      <div class="filed mt-3">
        <span class="font-weight-bold"><%= f.label :帰宅予定日時 %></span><br>
        <%= f.datetime_field :eta %>
      </div>
      <div class="filed mt-3">
        <span class="font-weight-bold"><%= f.label :申込締切 %></span><br>
        <%= f.datetime_field :preiod %>
      </div>
      <div class="filed mt-3">
        <span class="font-weight-bold"><%= f.label :募集人数 %></span><br>
        <%= f.select :recruitment, [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20], class: "event-filed" %>人
      </div>
      <div class="filed mt-3">
        <span class="font-weight-bold"><%= f.label :費用 %></span><br>
        <%= f.text_field :cost, placeholder: "0円", class: "event-filed" %>
      </div>
      <div class="filed mt-3">
        <span class="font-weight-bold"><%= f.label :目的地 %></span><br>
        <%= f.text_field :destination, placeholder: "野沢温泉スキー場、白馬八方尾根スキー場、苗場スキー場", class: "event-filed" %>
      </div>
      <div class="filed mt-3 text-left">
        <%= f.submit '作成', class: "btn btn-primary event-filed" %>
      </div>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<div class="row">
  <div class="col-sm-3 left-line">
    <%= render "devise/shared/back" %>
    <div class="side-bar">
      <%= render "devise/shared/side_links" %>
      <%= render "devise/shared/my_profile", current_user: @current_user %>
    </div>
  </div>
  <div class="col-sm-6 main py-4">
    <div class="eventer-profile">
      <%= link_to user_path(@event.user_id), class: "btn" do %>
        <%= attachment_image_tag @event.user, :profile_image, size: "50x50", fallback: 'no_image.jpg', format: 'jpeg', class: "rounded-circle" %>
        <span class="eventer-name ml-3"><%= @event.user.name %></span>
        <span class="eventer-sex ml-3 font-s"><%= @event.user.sex %></span>
      <% end %>
      <p class="font-s mt-1"><span><%= @event.created_at.strftime("%Y年%m月%d日") %></span>作成</p>
    </div>
    <hr>
    <div>
      <span class="font-weight-bold mr-2">出発予定日時:</span><%= @event.etd.strftime("%Y/%m/%d/%H:%M") %>
    </div>
    <hr>
    <div>
      <span class="font-weight-bold mr-2">帰宅予定日時:</span><%= @event.eta.strftime("%Y/%m/%d/%H:%M") %>
    </div>
    <hr>
    <div>
      <span class="font-weight-bold mr-2">申込締切日時:</span><%= @event.preiod.strftime("%Y/%m/%d/%H:%M") %>
    </div>
    <hr>
    <div>
      <span class="font-weight-bold mr-2">目的地:</span><%= @event.destination %>
    </div>
    <hr>
    <div>
      <span class="font-weight-bold mr-2">募集人数:</span><%= @event.recruitment %>人
    </div>
    <hr>
    <div>
      <span class="font-weight-bold mr-2">費用¥:</span><%= @event.cost %>
    </div>
    <hr>
    <div>
      <span class="font-weight-bold">タイトル</span>
      <p><%= @event.title %></p>
    </div>
    <hr>
    <div>
      <span class="font-weight-bold">詳細</span>
      <p><%= @event.content %></p>
    </div>
    <div>
      <% unless @user == current_user %>
      <% if @event.count_by?(@event) %><!--締切期限内で募集人数に達していないとき-->
      <!--申し込み済みかの確認-->
        <% if @event.applied_by?(current_user) %>
          <%= link_to event_event_users_path(id: @event.id, event_id: @event.id), method: :delete, data:
          {confirm: "参加をキャンセルしますか？</br>キャンセルする場合は必ず主催者様に事前にご連絡お願いします。", cancel: 'キャンセル', commit: '参加取消'}, title: '参加取消確認', class: "btn btn-danger btn-block" do %>
           <span>申し込み取消</span>
          <% end %>
        <% else %>
          <%= link_to event_event_users_path(id: @event.id, event_id: @event.id), method: :post, data:
          {confirm: "参加を申し込みますか？</br>申し込み後にキャンセルされる場合は主催者様に必ずご連絡お願いします。", cancel: 'キャンセル', commit: '参加する'}, title: '参加申込確認', class: "btn btn-primary btn-block" do %>
          <span>申し込み</span>
          <% end %>
        <% end %>
      <% else %><!--締切期限後か募集人数に達した時-->
        <% if @event.applied_by?(current_user) %>
          <%= link_to event_event_users_path(id: @event.id, event_id: @event.id), method: :delete, data:
          {confirm: "参加をキャンセルしますか？</br>キャンセルする場合は必ず主催者様に事前にご連絡お願いします。", cancel: 'キャンセル', commit: '参加取消'}, title: '参加取消確認', class: "btn btn-danger btn-block" do %>
           <span>申し込み取消</span>
          <% end %>
        <% else %>
            <p class="text-center event-alert py-2">募集終了</p>
        <% end %>
      <% end %>
      <% end %>
    </div>
  </div>
  <div class="col-sm-3 right-bar">
    <div class="comment-form pb-3 mb-3">
      <h4 class="sub-title text-center py-1"><i class="fas fa-pencil-alt"></i>コメント</h4>
      <%= form_with(model:[@event, @event_comment], remote: true) do |f| %>
        <%= f.text_area :content, placeholder: "コメントを入力", class: 'content' %>
        <div  class="text-right">
          <%= f.submit('送信', class: "btn  btn-outline-primary post-comment-btn rounded-pill mt-1") %>
        </div>
      <% end %>
    </div>
    <div class="event-comments">
      <%= render '/events/event_comments', event: @event %>
    </div>
  </div>
</div>