config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#top'

  devise_for :users #controllers: {
  #   omniauth_callbacks: 'users/omniauth_callbacks'
  # }
  resources :users, only: [:show, :update, :new, :create, :edit] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  put "/users/:id/hide" => "users#hide", as: 'users_hide'
  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :rooms, only: [:create, :show, :index]
  resources :chats, only: [:create]
  resources :events do
    resource :event_users, only: [:create, :destroy]
    resources :event_comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

   validates :message, presence: true, length: { maximum: 80 }

end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :event_comments, dependent: :destroy
  has_many :event_users, dependent: :destroy

  validates :title, presence: true, length: { maximum: 38 }
  validates :content, presence: true
  validates :etd, presence: true
  validates :eta, presence: true
  validates :preiod, presence: true

  def count_by?(event)
    (event.recruitment > event.event_users.count) && event.preiod > Time.now
  end

  def applied_by?(user)
    event_users.where(user_id: user.id).exists?
  end

end

app/models/event_comment.rb
class EventComment < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :content, presence: true, length: { maximum: 120 }

end

app/models/event_user.rb
class EventUser < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :post
  
  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  attachment :post_image

  validates :content, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  attachment :image
  
  validates :content, presence: true, length: { maximum: 120 }
  
  def favorited_by?(user)  
    favorites.where(user_id: user.id).exists?
  end
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User" #followerモデルは存在しないためUserモデルをbelongs_toする
  belongs_to :followed, class_name: "User"

  validates :followed_id, presence: true
  validates :follower_id, presence: true

end

app/models/room.rb
class Room < ApplicationRecord

  has_many :entries, dependent: :destroy
  has_many :chats, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :sns_credentials, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :event_comments, dependent: :destroy
  has_many :event_users, dependent: :destroy

  attachment :profile_image

  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable, :timeoutable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed

  has_many :entries, dependent: :destroy
  has_many :chats, dependent: :destroy

  validates :name, presence: true, length: { in: 2..8 }, on: :update

  def follow(user_id) #フォローする
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id) #フォローを外す
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user) #フォローしていればtrue
    followings.include?(user)
  end

  def active_for_authentication? #退会済みなら弾く
    super && (self.is_delete == false)
  end

  # def self.without_sns_data(auth)
  #   user = User.where(email: auth.info.email).first

  #   if user.present?
  #     sns = SnsCredential.create(
  #       uid: auth.uid,
  #       provider: auth.provider,
  #       user_id: user.id
  #     )
  #   else
  #     user = User.new(
  #       # nickname: auth.info.name,
  #       email: auth.info.email,
  #     )
  #     sns = SnsCredential.new(
  #       uid: auth.uid,
  #       provider: auth.provider
  #     )
  #   end
  #   return { user: user ,sns: sns}
  # end

  # def self.with_sns_data(auth, snscredential)
  #   user = User.where(id: snscredential.user_id).first
  #   unless user.present?
  #     user = User.new(
  #       # nickname: auth.info.name,
  #       email: auth.info.email,
  #     )
  #   end
  #   return {user: user}
  # end

  # def self.find_oauth(auth)
  #   uid = auth.uid
  #   provider = auth.provider
  #   snscredential = SnsCredential.where(uid: uid, provider: provider).first
  #   if snscredential.present?
  #     user = with_sns_data(auth, snscredential)[:user]
  #     sns = snscredential
  #   else
  #     user = without_sns_data(auth)[:user]
  #     sns = without_sns_data(auth)[:sns]
  #   end
  #   return { user: user ,sns: sns}
  # end

  enum sex: { "男性" =>0, "女性" =>1 }
  enum style: { "スノーボーダー" =>0, "スキーヤー" =>1, "その他" =>2 }
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!

  def create
    @chat = current_user.chats.new(chat_params)
    if @chat.save
      redirect_to request.referer
    else
      flash[:alert] = "送信に失敗しました。"
      redirect_to request.referer
    end
  end

  private
  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @post = Post.new
    @posts = Post.all.order(created_at: :desc).page(params[:page]).per(10)
    @current_user = current_user
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path
    else
      flash[:alert] = "投稿に失敗しました。"
      redirect_to posts_path
    end
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @user = @post.user
    @current_user = current_user
  end

  def destroy
    # binding.pry
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "削除しました。"
  end

  private
  # ストロングパラメータ
  def post_params
    params.require(:post).permit(:content, :post_image)
  end

  def post_comment_params
    params.require(:post_comment).permit(:content, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/event_users_helper.rb
module EventUsersHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/posts/_contents.html.erb
<%= link_to post_path(post), class: "post-content" do %>
	<% if post.post_image.present? %>
		<p class="post-image"><%= attachment_image_tag(post, :post_image, size: "500", class: "img img-fluid") %></p>
	<% end %>
	<p class="post-text mt-3 ml-3"><%= truncate(post.content, length: 300) %></p>
<% end %>

app/views/posts/_form.html.erb
<div class="py-3 mb-4">
  <%= form_with model: post, remote: true do |f| %>
    <%= render "layouts/errors", model: post %>
    <div class="image_wrapper">
      <div class="item_image_btn">
        <%= f.attachment_field :post_image, id: "file" %>
      </div>
      <div id="img_field" onClick="$('#file').click()" >
        <i class="far fa-image"></i>
      </div>
    </div>
    <%= f.text_area :content, placeholder: "今何してる？", class: 'content' %>
  <div class="text-right mt-3 pb-2">
    <%= f.submit('投稿', class: "btn  btn-outline-primary post-btn rounded-pill") %>
  </div>
  <% end %>
</div>

app/views/posts/_icon.html.erb
<!--いいねあいこん-->
<% if post.favorited_by?(current_user) %>
  <%= link_to post_favorites_path(post), class: 'btn', method: :delete, remote: true do %>
    <i class="fa fa-heart favorite-btn ml-2"></i>
    <%= post.favorites.count %>
  <% end %>
<% else %>
  <%= link_to post_favorites_path(post), class: 'btn', method: :post, remote: true do %>
    <i class="fa fa-heart unfavorite-btn ml-2"></i>
    <%= post.favorites.count %>
  <% end %>
<% end %>
<!--こめんとあいこん-->
<%= link_to post_path(post), class: 'btn comment-icon' do %>
  <i class="far fa-comment-dots ml-2"></i>
 	<span><%= post.post_comments.count %></span>
<% end %>

app/views/posts/_index.html.erb
<!--プロフィール部分-->
<div class="profile-index mb-3">
  <%= render 'posts/profile', post: post %>
</div>
<!--投稿画像と内容-->
<div class="post-contents-index">
	<%= render 'posts/contents', post: post %>
</div>
<div id="bottons_<%= post.id %>">
  <%= render 'posts/icon', post: post %>
</div>

app/views/posts/_modal.html.erb
<!-- モーダル -->
<div class="modal fade mt-5" id="Modal" tabindex="-1" role="dialog" aria-labelledby="Modal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header py-0">
        <div>
          <%= link_to user_path(current_user), class: "btn left-btn" do %>
            <%= attachment_image_tag current_user, :profile_image, size: "50x50", fallback: 'no_image.jpg', format: 'jpeg',  class: "rounded-circle" %>
            <span><%= current_user.name %></span>
          <% end %>
        </div>
        <button type="button" class="close py-4" data-dismiss="modal" aria-label="閉じる">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_with model: post, remote: true do |f| %>
      <div class="modal-body">
        <%= render "layouts/errors", model: post %>
        <%= f.text_area :content, placeholder: "今何してる？", class: "textarea" %>
      </div>
      <div class="modal-footer">
        <%= f.label :post_image, class: "image-camera" do %>
        <i class="far fa-image mr-3"></i>
        <%= f.attachment_field :post_image %>
        <% end %>
        <%= f.submit('投稿', class: "btn  btn-outline-primary post-btn rounded-pill") %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/_post_comments.html.erb
<% post.post_comments.reverse.each do |post_comment| %>
  <div class="post-comment-index_<%= post_comment.id %>">
    <div class="commenter-profile">
      <%= link_to user_path(post_comment.user.id), class: "btn left-btn" do %>
        <%= attachment_image_tag post_comment.user, :profile_image, size: "50x50", fallback: 'no_image.jpg', format: 'jpeg', class: "rounded-circle" %>
        <span class="commenter-name-position"><%= post_comment.user.name %></span>
      <% end %>
    </div>
    <div>
      <div id="post-comment-form">
        <p class="text-center mt-3"><%= attachment_image_tag post_comment, :image, size: "250", format: 'jpeg', class: "img img-fluid" %></p>
        <p><%= post_comment.content %></p>
      </div>
      <% if post_comment.user == current_user %>
      <div>
        <%= link_to post_post_comment_path(post_comment.post, post_comment), method: :delete, remote: true do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
      <% end %>
    </div>
  <hr>
  </div>
<% end %>

app/views/posts/_profile.html.erb
<%= link_to user_path(post.user_id), class: "btn" do %>
  <%= attachment_image_tag post.user, :profile_image, size: "70x70", fallback: 'no_image.jpg', format: 'jpeg', class: "rounded-circle" %>
  <span class="profile-name-position ml-3"><%= post.user.name %></span>
<% end %>

app/views/posts/create.js.erb
$(".post-index").html("<%= j(render 'posts/index', post: @post) %>");
$("#post_content").val("");

app/views/posts/destroy.js.erb
$('.post-index_<%= @post.id %>').remove();

app/views/posts/index.html.erb
<div class="row">
   <!--サイドバー-->
  <div class="col-sm-3 left-line">
    <%= render "devise/shared/back" %>
    <div class="side-bar">
      <%= render "devise/shared/side_links" %>
      <!--モーダル-->
      <button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#Modal">
        投稿する
      </button>
      <%= render "devise/shared/my_profile", current_user: @current_user %>
    </div>
  </div>
  <!--メイン-->
  <div class="col-sm-9 main py-4">
    <h3 class="page-title text-center py-2 comment-form"><i class="fas fa-home"></i>ホーム</h3>
    <span class="font-s flash-error"><%= flash[:alert] %></span>
    <!--投稿フォーム-->
    <%= render '/posts/modal', post: @post, current_user: @current_user %><!--モーダル-->
    <%= render '/posts/form', post: @post %><!--一覧フォーム-->
    <div class="posts scroll-list jscroll">
      <!--投稿一覧-->
        <% @posts.each do |post| %>
          <div class="post-index_<%= post.id %>">
            <!--<#%= render 'posts/index', post: post %>-->
            <div class="profile-index mb-3">
              <%= render 'posts/profile', post: post %>
            </div>
            <!--投稿画像と内容-->
            <div class="post-contents-index">
            	<%= render 'posts/contents', post: post %>
            </div>
            <!--あいこんぼたん-->
            <div>
              <span id="bottons_<%= post.id %>"><%= render 'layouts/favorites_icon', post: post %></span>
              <span id="bottons_<%= post.id %>"><%= render 'layouts/comments_icon', post: post %></span>
              <span id="bottons_<%= post.id %>"><%= render 'layouts/delete_icon', post: post %></span>
            </div>
  <hr>
          </div>
        <% end %>
        <%= paginate @posts %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="row">
  <!--サイドバー-->
  <div class="col-sm-3 left-line">
    <%= render "devise/shared/back" %>
    <div class="side-bar">
      <%= render "devise/shared/side_links" %>
      <%= render "devise/shared/my_profile", current_user: @current_user %>
    </div>
  </div>
  <!--メイン-->
  <div class="col-sm-6 post-comment main pt-4 pb-4">
    <div class="post-show-profile decoration">
      <!--プルフィール-->
      <%= render 'users/profile', user: @user %>
    </div>
    <hr>
    <div class="mt-4 text-center">
      <%= attachment_image_tag @post, :post_image, size: '500', format: 'jpeg', class: "img img-fluid" %>
    </div>
    <div><!--あいこん-->
  		<span id="bottons_<%= @post.id %>"><%= render 'layouts/favorites_icon', post: @post %></span>
      <span id="comment_botton_<%= @post.id %>"><%= render 'layouts/comments_icon', post: @post %></span>
    </div>
    <div>
      <%= @post.content %>
    </div>
  </div>
  <!--コメント一覧-->
  <div class="col-sm-3 right-bar">
  <!--コメントフォーム-->
    <div class="comment-form pb-3 mb-3">
      <h4 class="sub-title text-center py-1"><i class="fas fa-pencil-alt"></i>コメント</h4>
      <%= form_with model:[@post, @post_comment] do |f| %>
        <%= f.label :image, class: "image-camera" do %>
        <i class="fas fa-camera"></i>
        <%= f.attachment_field :image %>
        <% end %>
        <%= f.text_area :content, placeholder: "コメントを入力(120文字以内)", class: 'content' %>
      <div class="text-right">
        <%= f.submit('送信', class: "btn  btn-outline-primary post-comment-btn rounded-pill mt-1") %>
      </div>
      <% end %>
    </div>
  <!--コメント表示-->
    <div class="post-comments">
      <%= render 'posts/post_comments', post: @post %>
    </div>
  </div>
</div>